#################################################################
# Makefile generated by Xilinx Platform Studio 
# Project:D:\casper10_1\projects\radix4\r4_iadc_spec\XPS_ROACH_base\system.xmp
#
# WARNING : This file will be re-generated every time a command
# to run a make target is invoked. So, any changes made to this  
# file manually, will be lost when make is invoked next. 
#################################################################

XILINX_EDK_DIR = /cygdrive/c/Xilinx/10.1/EDK
NON_CYG_XILINX_EDK_DIR = C:/Xilinx/10.1/EDK

SYSTEM = system

MHSFILE = system.mhs

MSSFILE = system.mss

FPGA_ARCH = virtex5

DEVICE = xc5vsx95tff1136-1

LANGUAGE = vhdl

SEARCHPATHOPT = 

SUBMODULE_OPT = 

PLATGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(SUBMODULE_OPT)

LIBGEN_OPTIONS = -mhs $(MHSFILE) -p $(DEVICE) $(SEARCHPATHOPT)

VPGEN_OPTIONS = -p $(DEVICE) $(SEARCHPATHOPT)

MANAGE_FASTRT_OPTIONS = -reduce_fanout no

OBSERVE_PAR_OPTIONS = -error yes

MICROBLAZE_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop.elf
PPC405_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc405/ppc_bootloop.elf
PPC440_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc440/ppc440_bootloop.elf
BOOTLOOP_DIR = bootloops

EPB_OPB_BRIDGE_INST_BOOTLOOP = $(BOOTLOOP_DIR)/epb_opb_bridge_inst.elf

BRAMINIT_ELF_FILES =  
BRAMINIT_ELF_FILE_ARGS =  

ALL_USER_ELF_FILES = 

SIM_CMD = vsim

BEHAVIORAL_SIM_SCRIPT = simulation/behavioral/$(SYSTEM)_setup.do

STRUCTURAL_SIM_SCRIPT = simulation/structural/$(SYSTEM)_setup.do

TIMING_SIM_SCRIPT = simulation/timing/$(SYSTEM)_setup.do

DEFAULT_SIM_SCRIPT = $(BEHAVIORAL_SIM_SCRIPT)

MIX_LANG_SIM_OPT = -mixed yes

SIMGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(BRAMINIT_ELF_FILE_ARGS) $(MIX_LANG_SIM_OPT)  -s mti -X D:/casper10_1/projects/radix4/r4_iadc_spec/XPS_ROACH_base/ -E D:/casper10_1/projects/radix4/r4_iadc_spec/XPS_ROACH_base/


LIBRARIES =  \
       epb_opb_bridge_inst/lib/libxil.a 
VPEXEC = virtualplatform/vpexec.exe

LIBSCLEAN_TARGETS = epb_opb_bridge_inst_libsclean 

PROGRAMCLEAN_TARGETS = 

CORE_STATE_DEVELOPMENT_FILES = D:\casper10_1\projects\radix4\r4_iadc_spec\XPS_ROACH_base\pcores\adc_interface_v1_01_a\netlist\adc_fifo.edn \
D:\casper10_1\projects\radix4\r4_iadc_spec\XPS_ROACH_base\pcores\adc_interface_v1_01_a\netlist\adc_fifo_fifo_generator_v2_2_xst_1.ngc \
D:\casper10_1\projects\radix4\r4_iadc_spec\XPS_ROACH_base\pcores\roach_infrastructure_v1_00_a\hdl\verilog\roach_infrastructure.v \
D:\casper10_1\projects\radix4\r4_iadc_spec\XPS_ROACH_base\pcores\reset_block_v1_00_a\hdl\verilog\reset_block.v \
D:\casper10_1\projects\radix4\r4_iadc_spec\XPS_ROACH_base\pcores\epb_opb_bridge_v1_00_a\hdl\verilog\epb_opb_bridge.v \
D:\casper10_1\projects\radix4\r4_iadc_spec\XPS_ROACH_base\pcores\epb_infrastructure_v1_00_a\hdl\verilog\epb_infrastructure.v \
D:\casper10_1\projects\radix4\r4_iadc_spec\XPS_ROACH_base\pcores\sys_block_v1_00_a\hdl\verilog\sys_block.v \
D:\casper10_1\projects\radix4\r4_iadc_spec\XPS_ROACH_base\pcores\opb_adccontroller_v1_00_a\hdl\verilog\adc_config_mux.v \
D:\casper10_1\projects\radix4\r4_iadc_spec\XPS_ROACH_base\pcores\opb_adccontroller_v1_00_a\hdl\vhdl\user_logic.vhd \
D:\casper10_1\projects\radix4\r4_iadc_spec\XPS_ROACH_base\pcores\opb_adccontroller_v1_00_a\hdl\vhdl\opb_adccontroller.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v2_00_a\hdl\vhdl\proc_common_pkg.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v2_00_a\hdl\vhdl\family.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v2_00_a\hdl\vhdl\or_muxcy.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v2_00_a\hdl\vhdl\or_gate.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v2_00_a\hdl\vhdl\counter_bit.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v2_00_a\hdl\vhdl\counter.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v2_00_a\hdl\vhdl\inferred_lut4.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v2_00_a\hdl\vhdl\srl_fifo2.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v2_00_a\hdl\vhdl\pf_counter_bit.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v2_00_a\hdl\vhdl\pf_counter.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v2_00_a\hdl\vhdl\pf_counter_top.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v2_00_a\hdl\vhdl\pf_occ_counter.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v2_00_a\hdl\vhdl\pf_occ_counter_top.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v2_00_a\hdl\vhdl\pf_adder_bit.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v2_00_a\hdl\vhdl\pf_adder.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v2_00_a\hdl\vhdl\pf_dpram_select.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v2_00_a\hdl\vhdl\srl16_fifo.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v2_00_a\hdl\vhdl\pselect.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v2_00_a\hdl\vhdl\valid_be.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v2_00_a\hdl\vhdl\ld_arith_reg.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v2_00_a\hdl\vhdl\mux_onehot.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v2_00_a\hdl\vhdl\down_counter.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v2_00_a\hdl\vhdl\ipif_pkg.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v2_00_a\hdl\vhdl\ipif_steer.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v2_00_a\hdl\vhdl\direct_path_cntr_ai.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\interrupt_control_v1_00_a\hdl\vhdl\interrupt_control.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\wrpfifo_v1_01_b\hdl\vhdl\pf_dly1_mux.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\wrpfifo_v1_01_b\hdl\vhdl\ipif_control_wr.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\wrpfifo_v1_01_b\hdl\vhdl\wrpfifo_dp_cntl.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\wrpfifo_v1_01_b\hdl\vhdl\wrpfifo_top.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\rdpfifo_v1_01_b\hdl\vhdl\ipif_control_rd.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\rdpfifo_v1_01_b\hdl\vhdl\rdpfifo_dp_cntl.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\rdpfifo_v1_01_b\hdl\vhdl\rdpfifo_top.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\opb_ipif_v3_01_a\hdl\vhdl\reset_mir.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\opb_ipif_v3_01_a\hdl\vhdl\brst_addr_cntr.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\opb_ipif_v3_01_a\hdl\vhdl\opb_flex_addr_cntr.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\opb_ipif_v3_01_a\hdl\vhdl\brst_addr_cntr_reg.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\opb_ipif_v3_01_a\hdl\vhdl\opb_be_gen.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\opb_ipif_v3_01_a\hdl\vhdl\srl_fifo3.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\opb_ipif_v3_01_a\hdl\vhdl\write_buffer.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\opb_ipif_v3_01_a\hdl\vhdl\opb_bam.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\opb_ipif_v3_01_a\hdl\vhdl\opb_ipif.vhd \
D:\casper10_1\projects\radix4\r4_iadc_spec\XPS_ROACH_base\pcores\opb_register_simulink2ppc_v1_00_a\hdl\vhdl\user_logic.vhd \
D:\casper10_1\projects\radix4\r4_iadc_spec\XPS_ROACH_base\pcores\opb_register_simulink2ppc_v1_00_a\hdl\vhdl\opb_register_simulink2ppc.vhd \
D:\casper10_1\projects\radix4\r4_iadc_spec\XPS_ROACH_base\pcores\opb_register_ppc2simulink_v1_00_a\hdl\vhdl\user_logic.vhd \
D:\casper10_1\projects\radix4\r4_iadc_spec\XPS_ROACH_base\pcores\opb_register_ppc2simulink_v1_00_a\hdl\vhdl\opb_register_ppc2simulink.vhd \
D:\casper10_1\projects\radix4\r4_iadc_spec\XPS_ROACH_base\pcores\adc_interface_v1_01_a\hdl\vhdl\adc_fifo.vhd \
D:\casper10_1\projects\radix4\r4_iadc_spec\XPS_ROACH_base\pcores\adc_interface_v1_01_a\hdl\vhdl\ddr_input.vhd \
D:\casper10_1\projects\radix4\r4_iadc_spec\XPS_ROACH_base\pcores\adc_interface_v1_01_a\hdl\vhdl\adc_interface.vhd \
D:\casper10_1\projects\radix4\r4_iadc_spec\XPS_ROACH_base\pcores\gpio_simulink2ext_v1_00_a\hdl\vhdl\gpio_simulink2ext.vhd \
D:\casper10_1\projects\radix4\r4_iadc_spec\XPS_ROACH_base\pcores\bram_if_v1_00_a\hdl\vhdl\bram_if.vhd

WRAPPER_NGC_FILES = implementation/infrastructure_inst_wrapper.ngc \
implementation/reset_block_inst_wrapper.ngc \
implementation/opb0_wrapper.ngc \
implementation/epb_opb_bridge_inst_wrapper.ngc \
implementation/epb_infrastructure_inst_wrapper.ngc \
implementation/sys_block_inst_wrapper.ngc \
implementation/opb_adccontroller_0_wrapper.ngc \
implementation/r4_iadc_spec_acc_cnt_wrapper.ngc \
implementation/r4_iadc_spec_acc_len_wrapper.ngc \
implementation/r4_iadc_spec_adc_wrapper.ngc \
implementation/r4_iadc_spec_cnt_rst_wrapper.ngc \
implementation/r4_iadc_spec_led0_sync_wrapper.ngc \
implementation/r4_iadc_spec_led1_new_acc_wrapper.ngc \
implementation/r4_iadc_spec_snap_adc_addr_wrapper.ngc \
implementation/r4_iadc_spec_snap_adc_bram_ramif_wrapper.ngc \
implementation/r4_iadc_spec_snap_adc_bram_ramblk_wrapper.ngc \
implementation/r4_iadc_spec_snap_adc_bram_wrapper.ngc \
implementation/r4_iadc_spec_snap_adc_ctrl_wrapper.ngc \
implementation/r4_iadc_spec_snap_vacc0_addr_wrapper.ngc \
implementation/r4_iadc_spec_snap_vacc0_bram_ramif_wrapper.ngc \
implementation/r4_iadc_spec_snap_vacc0_bram_ramblk_wrapper.ngc \
implementation/r4_iadc_spec_snap_vacc0_bram_wrapper.ngc \
implementation/r4_iadc_spec_snap_vacc0_ctrl_wrapper.ngc \
implementation/r4_iadc_spec_snap_vacc1_addr_wrapper.ngc \
implementation/r4_iadc_spec_snap_vacc1_bram_ramif_wrapper.ngc \
implementation/r4_iadc_spec_snap_vacc1_bram_ramblk_wrapper.ngc \
implementation/r4_iadc_spec_snap_vacc1_bram_wrapper.ngc \
implementation/r4_iadc_spec_snap_vacc1_ctrl_wrapper.ngc \
implementation/r4_iadc_spec_snap_vacc2_addr_wrapper.ngc \
implementation/r4_iadc_spec_snap_vacc2_bram_ramif_wrapper.ngc \
implementation/r4_iadc_spec_snap_vacc2_bram_ramblk_wrapper.ngc \
implementation/r4_iadc_spec_snap_vacc2_bram_wrapper.ngc \
implementation/r4_iadc_spec_snap_vacc2_ctrl_wrapper.ngc \
implementation/r4_iadc_spec_snap_vacc3_addr_wrapper.ngc \
implementation/r4_iadc_spec_snap_vacc3_bram_ramif_wrapper.ngc \
implementation/r4_iadc_spec_snap_vacc3_bram_ramblk_wrapper.ngc \
implementation/r4_iadc_spec_snap_vacc3_bram_wrapper.ngc \
implementation/r4_iadc_spec_snap_vacc3_ctrl_wrapper.ngc \
implementation/r4_iadc_spec_sync_cnt_wrapper.ngc

POSTSYN_NETLIST = implementation/$(SYSTEM).ngc

SYSTEM_BIT = implementation/$(SYSTEM).bit

DOWNLOAD_BIT = implementation/download.bit

SYSTEM_ACE = implementation/$(SYSTEM).ace

UCF_FILE = data/system.ucf

BMM_FILE = implementation/$(SYSTEM).bmm

BITGEN_UT_FILE = etc/bitgen.ut

XFLOW_OPT_FILE = etc/fast_runtime.opt
XFLOW_DEPENDENCY = __xps/xpsxflow.opt $(XFLOW_OPT_FILE)

XPLORER_DEPENDENCY = __xps/xplorer.opt
XPLORER_OPTIONS = -p $(DEVICE) -uc $(SYSTEM).ucf -bm $(SYSTEM).bmm -max_runs 7

FPGA_IMP_DEPENDENCY = $(BMM_FILE) $(POSTSYN_NETLIST) $(UCF_FILE) $(XFLOW_DEPENDENCY)
