function child=find_by_name(parent,name)
% Finds a child block by name.
%
% find_by_name( parent, name )
%
% parent = The parent subsystem
% name = The name of the desired child block
%
% Finds a child block by name using find_system rather than just
% appending the child name to the parent.  If parent is empty, search through
% a predefined list of libraries/subsystems for a block named name.
%
% Libraries searched: newfft_library


  if isempty(parent)
    parent={ ...
      'newfft_library/Butterfly', ...
      'newfft_library/Delay', ...
      'newfft_library/FFT', ...
      'newfft_library/FIR', ...
      'newfft_library/Math', ...
      'newfft_library/Reorder', ...
      'newfft_library/Twiddle', ...
      'newfft_library/Utility' ...
    };
  end

  child = find_system(parent, ...
    'SearchDepth',      1 , ...
    'LookUnderMasks', 'all', ...
    'FollowLinks',    'on', ...
    'Name',          name);

  if iscell(child) && ~isempty(child)
    child=child{1};
  end
